language: android

sudo: false

jdk: oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.3
    - extra-android-m2repository
    - extra-google-android-support

    # The SDK version used to compile your project
    - android-25

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-25

os: linux
